### PR TITLE
Firmware 5.9 parsing is added.

### PR DESCRIPTION
**Pull request by Byeongdulee**
Parsing of Firmware 5.9 is added to urrtmon. Would you like to merge?

### CODE REVIEW

**Comment by oroulet** [comment]
change in urrtmon are fine, but you still have these files .history which have nothing to do here. I supposed they are files from your editor or something similar...

**Comment by Byeongdulee** [comment]
Those are probably generated by vscode. I will put it in .gitignore.

**Comment by Byeongdulee** [comment]
removed .history. Is it ok now?

**Comment by oroulet** [comment]
good now it looks ok

**Pull request merged**
